# Generated by Django 5.0.6 on 2025-03-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miskoris_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forest',
            name='polygon_coords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
