# Generated by Django 5.0.6 on 2025-03-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miskoris_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('random_text', models.CharField(max_length=255)),
                ('random_float', models.FloatField()),
            ],
        ),
    ]
