# Generated by Django 5.0.6 on 2025-03-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miskoris_app', '0002_testclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
