# Generated by Django 5.0.6 on 2025-03-25 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miskoris_app', '0004_forest_image_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forest_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='miskoris_app.forest')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='miskoris_app.order')),
            ],
        ),
    ]
