# Generated by Django 5.0.6 on 2025-03-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miskoris_app', '0005_forest_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest_document',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
