# Generated by Django 5.0.6 on 2025-03-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miskoris_app', '0006_alter_forest_document_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forest_document',
            name='order',
        ),
        migrations.AlterField(
            model_name='forest_document',
            name='document',
            field=models.BinaryField(),
        ),
    ]
