# Generated by Django 5.1.7 on 2025-03-27 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miskoris_app', '0008_forest_document_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('analysis_result', models.TextField(blank=True, null=True)),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzed_images', to='miskoris_app.forest')),
                ('original_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_versions', to='miskoris_app.forest_image')),
            ],
        ),
    ]
