# Generated by Django 5.0.6 on 2025-04-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miskoris_app', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
