# Generated by Django 5.0.6 on 2025-04-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miskoris_app', '0011_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='forest_image',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forest_image',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
