# Generated by Django 5.0.6 on 2025-05-22 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miskoris_app', '0015_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='miskoris_app.forest')),
            ],
        ),
    ]
